server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:secret@localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andifalk/cloud-config-repository
security:
  user:
    name: config
    password: secret

encrypt:
  keyStore:
    location: classpath:/configserver.jks
    password: secret
    alias: configserver
    secret: secret